# Copied from tm12_moveit_config, adding use_sim_time
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    
    tmr_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      # type: forward_command_controller/ForwardCommandController
 
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

tmr_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

